apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"
  
configMapGenerator:
  - name: app-config
    envs:
      - .env

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: nathan-app
    patch: |-
      - op: replace
        path: /spec/host
        value: nathan-app.dev.ocp4.lab
    