apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

namePrefix: dev-

replacements:
  - source:
      kind: Service
      name: nginx-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Route
        fieldPaths: 
          - spec.to.name
  - source:
      kind: Pod
      name: nginx-pod
      fieldPath: metadata.labels.app
    targets:
      - select:
          kind: Service
        fieldPaths: 
          - spec.selector.app 
          
configMapGenerator:
  - name: app-config
    envs:
      - .env

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: dev-nginx-route
    patch: |-
      - op: replace
        path: /spec/host
        value: dev-nathan-nginx.apps-crc.testing
  - target:
      group: v1
      version: v1
      kind: Pod
      name: nginx-pod
    patch: |- 
      - op: add
        path: /metadata/labels/app
        value: dev-nginx 
    