apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nathan-ns

resources:
  - "../../base"

namePrefix: dev-

configMapGenerator:
  - name: generated-application-configmap
    envs:
      - .env
      
replacements:
  - source:
      kind: Service
      name: application-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Route
        fieldPaths: 
          - spec.to.name
  - source:
      kind: Deployment
      name: application-deployment
      fieldPath: spec.template.metadata.labels.app
    targets:
      - select:
          kind: Service
        fieldPaths: 
          - spec.selector.app

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: application-route
    patch: |-
      - op: replace
        path: /spec/host
        value: dev-application.apps-crc.testing
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: application-deployment
    patch: |- 
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dev-application-imagestream:dev
      - op: replace
        path: /spec/selector/matchLabels/app
        value: application-pod-label
      - op: replace
        path: /spec/template/metadata/labels/app
        value: application-pod-label
  - target:
      group: image.openshift.io
      version: v1
      kind: ImageStream
      name: application-imagestream
    patch: |- 
      - op: replace
        path: /spec/tags/0/name
        value: dev