apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
  namespace: nathan-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: node

  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: natewilcox/node-server:1.0.0
        imagePullPolicy: IfNotPresent
        name: node-server
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: super-user
      serviceAccountName: super-user