apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    envs:
      - .env

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
    patch: |-
      - op: replace
        path: /spec/host
        value: prod-nathan-nginx.apps-crc.testing