apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

namePrefix: prod-

configMapGenerator:
  - name: app-config
    envs:
      - .env
      
replacements:
  - source:
      kind: Service
      name: application-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Route
        fieldPaths: 
          - spec.to.name
  - source:
      kind: Deployment
      name: application-deployment
      fieldPath: metadata.labels.app
    targets:
      - select:
          kind: Service
        fieldPaths: 
          - spec.selector.app

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: application-route
    patch: |-
      - op: replace
        path: /spec/host
        value: prod-application.apps-crc.testing
  - target:
      group: apps.openshift.io
      version: v1
      kind: Deployment
      name: application-deployment
    patch: |- 
      - op: replace
        path: /spec/selector/app
        value: prod-application-pod
      - op: replace
        path: /spec/template/metadata/labels/app
        value: prod-application-pod
      - op: replace
        path: /metadata/labels/app
        value: prod-application-deployment-label