apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: namespace-manager
  namespace: nathan-project-ns
  
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-manager-binding
  namespace: nathan-project-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-manager
subjects:
- kind: ServiceAccount
  name: argocd-nathan-sample-argocd-application-controller
  namespace: nathan-project