apiVersion: apps/v1
kind: Deployment

metadata:
  name: application-deployment
  labels: 
    app: placeholder123

spec:
  replicas: 1

  selector:
    matchLabels:
      app: placeholder333

  template:
    metadata:
      labels:
        app: placeholder333
    spec:
      serviceAccountName: super-user
      containers:
      - name: application-container
        image: natewilcox/node_server:1.0.5
        ports:
        - containerPort: 8080