apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-label

  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - image: natewilcox/node-server:1.0.0
        imagePullPolicy: IfNotPresent
        name: node-server
      serviceAccountName: super-user