apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - image: natewilcox/node-server:1.0.3
        imagePullPolicy: IfNotPresent
        name: node-server
        env:
          - name: label
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: label 

      serviceAccountName: super-user