apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - image: natewilcox/node-server:1.0.1
        imagePullPolicy: IfNotPresent
        name: node-server
        envFrom:
        - configMapRef:
            name: deployment-app-config
      serviceAccountName: super-user