apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      volumes:
      - name: application-configmap
        configMap:
          name: application-configmap
      containers:
      - name: application-image
        
        volumeMounts:
        - name: application-configmap
          mountPath: /usr/src/app/config
          readOnly: true
        env:
          - name: label
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: label 

      serviceAccountName: super-user

  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - application-image
      from:
        kind: ImageStreamTag
        name: dev-application-imagestream:dev
        namespace: nathan-ns