apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-label
  name: deployment
  namespace: nathan-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-pod-label

  template:
    metadata:
      labels:
        app: deployment-pod-label
    spec:
      containers:
      - image: natewilcox/node-server:1.0.0
        imagePullPolicy: IfNotPresent
        name: node-server
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: super-user
      serviceAccountName: super-user