apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      volumes:
      - name: application-configmap
        configMap:
          name: application-configmap
      containers:
        # In order to use an imagestream in a deployment, you must use the Docker image reference
        # you can get this with the command: oc get istag/dev-application-imagestream:dev -o jsonpath='{.image.dockerImageReference}'
      - name: application-image
        image: natewilcox/node-server@sha256:1ad0908f4ed2e6a8e11ebcc436ce07b812c2d62a4b6316c3cd141a7a7b234caf
        volumeMounts:
        - name: application-configmap
          mountPath: /usr/src/app/config
          readOnly: true
        env:
          - name: label
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: label 

      serviceAccountName: super-user