apiVersion: apps.openshift.io/v1
kind: DeploymentConfig

metadata:
  name: application-deployment
  labels: 
    app: placeholder

spec:
  replicas: 1
  selector:
    app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - name: application-container
        image: natewilcox/node_server:1.0.0
        ports:
        - containerPort: 8080

  triggers:
  - type: ConfigChange