apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      volumes:
      - name: application-configmap
        configMap:
          name: application-configmap
      containers:
      - name: application-image
        image: natewilcox/node-server@sha256:036b2fbbf92110154027d7b03f6b1ca98e61192acc4424d7ae61704a9665db52
        volumeMounts:
        - name: application-configmap
          mountPath: /usr/src/app/config
          readOnly: true
        env:
          - name: label
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: label 

      serviceAccountName: super-user