apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-deployment-label
  name: application-deployment
  namespace: nathan-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: placeholder

  template:
    metadata:
      labels:
        app: placeholder
    spec:
      volumes:
      - name: application-configmap
        configMap:
          name: application-configmap
      containers:
        # In order to use an imagestream in a deployment, you must use the Docker image reference
        # you can get this with the command: oc get istag/dev-application-imagestream:dev -o jsonpath='{.image.dockerImageReference}'

        # ***Steps to update the imagestream***: 
        # 1. Import the new image - oc import-image dev-application-imagestream:1.0.7 --from=natewilcox/node-server:1.0.7 --confirm
        # 2. Tag the new image - oc tag dev-application-imagestream:1.0.7 dev-application-imagestream:dev
      - name: application-image
        image: placeholder
        volumeMounts:
        - name: application-configmap
          mountPath: /usr/src/app/config
          readOnly: true
        env:
          - name: label
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: label 

      # serviceAccountName: super-user