apiVersion: image.openshift.io/v1
kind: ImageStream

metadata:
  name: application-imagestream
  namespace: nathan-ns

spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: natewilcox/node-server:1.0.5
    importPolicy:
      scheduled: true