apiVersion: image.openshift.io/v1
kind: ImageStream

metadata:
  name: application-imagestream
  namespace: nathan-ns

spec:
  tags:
  - name: dev
    from:
      kind: DockerImage
      name: natewilcox/node-server:1.0.3
    importPolicy:
      scheduled: true