apiVersion: image.openshift.io/v1
kind: ImageStream

metadata:
  name: application-imagestream
  namespace: nathan-ns

spec:
  localPolicy:
    local: false
  tags:
  - name: dev
    from:
      kind: DockerImage
      name: natewilcox/node-server:1.0.5
    importPolicy:
      scheduled: true
    resourcePolicy:
      type: Source