apiVersion: v1
kind: Pod

metadata:
  name: application-pod
  labels:
    app: placeholder

spec:
  containers:
  - name: node-server-container
    image: nginx
    ports:
    - containerPort: 80
    env: