apiVersion: route.openshift.io/v1
kind: Route

metadata:
  name: application-route
  
spec:
  host: dev-application.apps-crc.testing
  to:
    kind: Service
    name: placeholder
    
  port:
    targetPort: 80