apiVersion: route.openshift.io/v1
kind: Route

metadata:
  labels:
    app: application-route-label
  name: application-route
  namespace: nathan-ns

spec:
  host: node-nathan-ns.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: application-service