apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-service-label
  name: deployment-service
  namespace: nathan-ns

spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node
  sessionAffinity: None
  type: ClusterIP