apiVersion: v1
kind: Service
metadata:
  labels:
    app: application-service-label
  name: application-service
  namespace: nathan-ns

spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pod-label