apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: deployment
  
spec:

  destination:
    namespace: nathan-ns
    server: "https://kubernetes.default.svc"
    
  project: nathans-ns
  
  source:
    repoURL: https://github.com/natewilcox/ocp_test.git 
    path: overlays/deployment
    targetRevision: master
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

  depends_on:
  - target:
      apiVersion: v1
      kind: ConfigMap
      name: app-config