apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev
  
spec:

  destination:
    namespace: nathan-ns
    server: "https://kubernetes.default.svc"
    
  project: nathans-ns
  
  source:
    repoURL: https://github.com/natewilcox/ocp_test.git 
    path: overlays/dev
    targetRevision: master
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: image.openshift.io
      kind: ImageStream
      jsonPointers:
        - /spec/tags/0/from/name